#!/usr/bin/env node
console.log('Getting list of plugin updates...');

const spawnSync = require('child_process').spawnSync;

const gitTopLevelPath = spawnSync('git', ['rev-parse', '--show-toplevel'], { encoding : 'utf8' });
const landoWPPluginPath = spawnSync('lando', ['wp', 'plugin', 'path'], { encoding : 'utf8' });
const gitAddPluginsPath = `${gitTopLevelPath.stdout.trim()}/${landoWPPluginPath.stdout.trim().split('./')[1]}`;

const landoWPPluginUpdatePluginsJSON = spawnSync('lando', ['wp', 'plugin', 'update', '--all', '--dry-run', '--format=json'], { encoding : 'utf8' });
let pluginsData = [];
let updatedPluginList = [];
let erroredPluginList = [];

try {
  pluginsData = JSON.parse(landoWPPluginUpdatePluginsJSON.stdout);
}
catch (e) {
  console.log('Error getting list of plugin updates.');
  console.log(landoWPPluginUpdatePluginsJSON);
  // console.log(landoWPPluginUpdatePluginsJSON.stdout);
}

console.log('Updating plugins...\n');

for (let plugin of pluginsData) {
  let landoWPPluginUpdatePluginJSON = spawnSync('lando', ['wp', 'plugin', 'update', plugin.name, '--format=json'], { encoding : 'utf8' });
  let resultData;

  try {
    resultData = JSON.parse(landoWPPluginUpdatePluginJSON.stdout);
  } catch (e) {
    // console.log(e);
    console.log(landoWPPluginUpdatePluginJSON.stdout);
    console.log(`Error updating plugin ${plugin.name} from ${plugin.version} to ${plugin.update_version}`);
    continue;
  }

  if (resultData[0].status == 'Updated') {
    const gitAdd = spawnSync('git', ['add', `${gitAddPluginsPath}/${plugin.name}`], { encoding : 'utf8' });
    let gitAddData;

    try {
      gitAddData = gitAdd;
      // gitAddData = JSON.parse(gitAdd.stdout);
    }
    catch (e) {
      console.log('Error commiting plugin update.');
      console.log(gitAddData);
      console.log(gitAddData.stdout);
    }

    spawnSync('git', ['commit', '-m', `Update plugin ${plugin.name} from ${plugin.version} to ${plugin.update_version}`]);
    console.log(`Update plugin ${plugin.name} from ${plugin.version} to ${plugin.update_version}`);
    updatedPluginList.push(plugin);
  } else {
    console.log(`Error updating plugin ${plugin.name} from ${plugin.version} to ${plugin.update_version}`);
    erroredPluginList.push(plugin);
  }
}

console.log(`\n${updatedPluginList.length} Plugins Updated`);

if (updatedPluginList.length) {
  console.log('Updated plugins:');
  for (let updatedPlugin of updatedPluginList) {
    console.log(`${updatedPlugin.name} from ${updatedPlugin.version} to ${updatedPlugin.update_version}`);
  }
}

if (erroredPluginList.length) {
  console.log(`\n${erroredPluginList.length} Plugins Errored`);
  for (let erroredPlugin of erroredPluginList) {
    console.log(`${erroredPlugin.name} from ${erroredPlugin.version} to ${erroredPlugin.update_version}`);
  }
}
