#!/usr/bin/env node

console.log('Getting list of theme updates...');

const spawnSync = require('child_process').spawnSync;

const updatePath = spawnSync('wp', ['plugin', 'path'], { encoding : 'utf8' });

// const gitPath = spawnSync('git', ['rev-parse', '--show-toplevel'], { encoding : 'utf8' });
// const gitAddPath = `${gitPath.stdout.trim()}/${updatePath.stdout.trim().split('./')[1]}`;
const gitAddPath = updatePath.stdout.trim();

const updateJSON = spawnSync('wp', ['theme', 'update', '--all', '--dry-run', '--format=json'], { encoding : 'utf8' });
let updateData = [];
let updateList = [];
let errorList = [];

try {
  updateData = JSON.parse(updateJSON.stdout);
} catch (e) {
  console.log('Error getting list of theme updates.');
  console.log(e);
  // console.log(updateJSON);
  console.log(updateJSON.stdout);
}

console.log('Updating themes...\n');

for (let theme of updateData) {
  let updateJSON = spawnSync('wp', ['theme', 'update', theme.name, '--format=json'], { encoding : 'utf8' });
  let resultData;

  try {
    resultData = JSON.parse(updateJSON.stdout);
  } catch (e) {
    // console.log(e);
    console.log(`Error updating theme ${theme.name} from ${theme.version} to ${theme.update_version}`);
    console.log(e);
    console.log(updateJSON.stdout);
    continue;
  }

  if (resultData[0].status == 'Updated') {
    const gitAdd = spawnSync('git', ['add', `${gitAddPath}/${theme.name}`], { encoding : 'utf8' });
    let gitAddData;

    try {
      gitAddData = gitAdd;
      // gitAddData = JSON.parse(gitAdd.stdout);
    } catch (e) {
      // console.log(e);
      console.log('Error commiting theme update.');
      console.log(gitAddData);
      console.log(gitAddData.stdout);
    }

    spawnSync('git', ['commit', '-m', `Update theme ${theme.name} from ${theme.version} to ${theme.update_version}`]);
    console.log(`Update theme ${theme.name} from ${theme.version} to ${theme.update_version}`);
    updateList.push(theme);
  } else {
    console.log(`Error updating theme ${theme.name} from ${theme.version} to ${theme.update_version}`);
    errorList.push(theme);
  }
}

console.log(`\n${updateList.length} Themes Updated`);

if (updateList.length) {
  for (let theme of updateList) {
    console.log(`${theme.name} from ${theme.version} to ${theme.update_version}`);
  }
}

if (errorList.length) {
  console.log(`\n${errorList.length} Theme Update Errors`);

  for (let theme of errorList) {
    console.log(`${theme.name} from ${theme.version} to ${theme.update_version}`);
  }
}
